// <auto-generated />
using System;
using SnoopRatt.App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SnoopRatt.App.Migrations
{
    [DbContext(typeof(MaryJaneContext))]
    [Migration("20220803070430_UpdateUsersTableRenameAlertOnLevelUpColumn")]
    partial class UpdateUsersTableRenameAlertOnLevelUpColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("MaryJaneBud.App.Entities.GuildSettings", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("MaryJaneBud.App.Entities.Ping", b =>
                {
                    b.Property<ulong>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Xp")
                        .HasColumnType("REAL");

                    b.HasKey("MessageId");

                    b.HasIndex("TimeStamp");

                    b.HasIndex("UserId");

                    b.ToTable("Pings");
                });

            modelBuilder.Entity("MaryJaneBud.App.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnLevelUp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Xp")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MaryJaneBud.App.Entities.Ping", b =>
                {
                    b.HasOne("MaryJaneBud.App.Entities.User", "User")
                        .WithMany("Pings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaryJaneBud.App.Entities.User", b =>
                {
                    b.Navigation("Pings");
                });
#pragma warning restore 612, 618
        }
    }
}
